# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20151205_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Desired order in the list; ascending (i.e. 0 = topmost)', verbose_name='List Order'),
        ),
    ]
