# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_subject_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.FileField(blank=True, help_text='Subject icon to be displayed along with Subject name', null=True, upload_to='uploads/subject_icons/'),
        ),
    ]
