# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0010_auto_20170827_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='\u0411\u0430\u0493\u0430\u0441\u044b')),
                ('listing_order', models.PositiveSmallIntegerField(default=0, verbose_name='Listing Order')),
            ],
            options={
                'ordering': ['listing_order'],
                'verbose_name': 'Quiz Package',
                'verbose_name_plural': 'Quiz Packages',
            },
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.SmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['subject', 'name'], 'verbose_name': 'Quiz/Test', 'verbose_name_plural': 'Quizzes/Tests'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(blank=True, help_text='Answer content', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, help_text='Question text', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, help_text='Image to go with problem statement', null=True, upload_to='uploads/question/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Solution content', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='solutionfigure',
            field=models.ImageField(blank=True, help_text='Solution in the form of image', null=True, upload_to='uploads/question/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u0411\u0430\u0493\u0430\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='package',
            name='quizzes',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
