# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_dayindalushy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.SmallIntegerField(default=0, verbose_name='$'),
        ),
    ]
